from __future__ import annotations

import json
import threading
from datetime import UTC, datetime
from pathlib import Path
from typing import Mapping

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from .models import ShadowPolicy
from .signing import verify_shadow_policy_token


class SignedPolicyFileStore:
    """Atomically reload short-lived tokens generated by the local policy agent."""

    def __init__(
        self,
        path: Path,
        *,
        expected_issuer: str,
        expected_audience: str,
        trusted_public_keys: Mapping[str, Ed25519PublicKey],
        revoked_policy_ids: set[str] | None = None,
    ) -> None:
        self.path = path
        self.expected_issuer = expected_issuer
        self.expected_audience = expected_audience
        self.trusted_public_keys = trusted_public_keys
        self.revoked_policy_ids = revoked_policy_ids or set()
        self._lock = threading.Lock()
        self._last_mtime_ns: int | None = None
        self._policies: dict[str, ShadowPolicy] = {}

    def get_policies(self, *, now: datetime | None = None) -> dict[str, ShadowPolicy]:
        now = (now or datetime.now(UTC)).astimezone(UTC)
        with self._lock:
            mtime_ns = self.path.stat().st_mtime_ns
            if mtime_ns != self._last_mtime_ns:
                document = json.loads(self.path.read_text())
                tokens = document.get("tokens")
                if not isinstance(tokens, list):
                    raise ValueError("Policy file must contain a tokens array.")
                loaded: dict[str, ShadowPolicy] = {}
                for token in tokens:
                    policy = verify_shadow_policy_token(
                        token,
                        expected_issuer=self.expected_issuer,
                        expected_audience=self.expected_audience,
                        trusted_public_keys=self.trusted_public_keys,
                        revoked_policy_ids=self.revoked_policy_ids,
                        now=now,
                    )
                    if policy.scope_id in loaded:
                        raise ValueError(f"Multiple active policies supplied for scope {policy.scope_id}.")
                    loaded[policy.scope_id] = policy
                self._policies = loaded
                self._last_mtime_ns = mtime_ns
            return {
                scope_id: policy
                for scope_id, policy in self._policies.items()
                if policy.not_after > now
            }
